(function(){
'use strict';
const Book=JSON.parse(document.getElementById('book-data').textContent);
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chapter=id=>Book.chapters.find(c=>c.id===id),source=id=>Book.sources.find(s=>s.id===id),lab=id=>Book.labs.find(l=>l.id===id);
const Key='strata-textbook.v1';
const initial=()=>({schema:1,track:'engineering',theme:'light',fontSize:17,completed:[],bookmarks:[],notes:{},answers:{},experiments:[],last:'01'});
function validate(s){
 if(!s||typeof s!=='object'||s.schema!==1)throw new Error('不是可识别的学习记录（schema 1）');const v=initial();
 v.track=Book.tracks.some(t=>t.id===s.track)?s.track:'engineering';v.theme=['light','dark'].includes(s.theme)?s.theme:'light';v.fontSize=[15,16,17,18,19,20,21].includes(s.fontSize)?s.fontSize:17;
 for(const key of ['completed','bookmarks']){if(s[key]!==undefined&&!Array.isArray(s[key]))throw new Error(`${key} 应为数组`);v[key]=[...new Set((s[key]||[]).filter(id=>!!chapter(id)))];}
 v.last=chapter(s.last)?s.last:'01';
 for(const [id,text] of Object.entries(s.notes||{})){if(chapter(id)&&typeof text==='string'&&text.length<=100000)v.notes[id]=text;}
 for(const [key,a] of Object.entries(s.answers||{})){if(/^\d{2}:[0-2]$/.test(key)&&chapter(key.slice(0,2))&&a&&Number.isInteger(a.choice)&&a.choice>=0&&a.choice<=2)v.answers[key]={choice:a.choice,checked:a.checked===true};}
 if(Array.isArray(s.experiments))for(const e of s.experiments.slice(-40)){if(e&&lab(e.lab)&&typeof e.time==='string'&&typeof e.params==='object'&&typeof e.result==='object'&&JSON.stringify(e).length<100000)v.experiments.push(JSON.parse(JSON.stringify(e)));}
 return v;
}
let state=initial(),storageOK=true;
try{const raw=localStorage.getItem(Key);if(raw)state=validate(JSON.parse(raw));}catch(e){storageOK=false;}
let toastTimer=null,observer=null,labSnapshot=null;
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3000);}
function storageNotice(){const n=$('#storage-alert');if(n)n.hidden=storageOK;}
function save(){try{localStorage.setItem(Key,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;}storageNotice();return storageOK;}
function settings(){document.documentElement.dataset.theme=state.theme;document.documentElement.style.setProperty('--reading-size',state.fontSize+'px');$('#theme-button').textContent=state.theme==='light'?'◐':'◑';$('#theme-button').setAttribute('aria-label',state.theme==='light'?'切换深色主题':'切换浅色主题');}
function refs(html){return html.replace(/\[((?:S|R)\d{2})\]/g,(m,id)=>source(id)?`<a class="ref" href="#source/${id}" title="${esc(source(id).title)}">${id}</a>`:m);}
function wrapTables(html){return html.replace(/<table>/g,'<div class="table-wrap"><table>').replace(/<\/table>/g,'</table></div>');}
function bodyHTML(html){return wrapTables(refs(html));}
function footer(){return `<footer class="footer"><span>从 Strata 学推理系统 · 独立 Web 教材<br>v${Book.provenance.edition} / ${Book.provenance.date} · 未经正式同行外审<br><a href="${esc(Book.provenance.authorUrl)}" target="_blank" rel="noopener noreferrer">${esc(Book.provenance.author)}</a> · ${esc(Book.provenance.license)} · <a href="${esc(Book.provenance.repoUrl)}" target="_blank" rel="noopener noreferrer">GitHub</a></span><span>源码锚点 <a href="https://github.com/Niko1221/Strata/tree/${Book.provenance.commit}" target="_blank" rel="noopener noreferrer">${Book.provenance.commit.slice(0,12)}</a><br><a href="#sources">证据边界与来源</a> · <a href="#notes">记录仅存本机，可导出</a></span></footer>`;}
function draftNote(){return `<div class="draft-note" role="note"><strong>初版</strong> · AI 辅助编写 · 未经同行审阅 · 发现错误请<a href="${esc(Book.provenance.issues)}" target="_blank" rel="noopener noreferrer">提交勘误 ↗</a></div>`;}
function scope(){return `<div class="scope-note"><strong>阅读约定</strong> · 基础原理、固定代码、上游报告和教学推演分别标注。${esc(Book.provenance.scope)} 浏览器实验不调用模型，数字不是硬件实测。</div>`;}
function renderSidebar(current){
 const old=$('.side-scroll'),scroll=old?old.scrollTop:0,t=Book.tracks.find(t=>t.id===state.track),chs=Book.chapters.filter(c=>t.chapters.includes(c.id));
 $('#sidebar').innerHTML=`<div class="side-top"><span class="eyebrow">LEARNING PATH / 学习路线</span><label class="sr-only" for="track-select">选择学习路线</label><select id="track-select">${Book.tracks.map(t=>`<option value="${t.id}" ${state.track===t.id?'selected':''}>${t.name} · ${t.chapters.length} 章</option>`).join('')}</select><div class="side-links"><a href="#map">课程关联图</a><a href="#glossary">术语表</a></div></div><nav class="side-scroll" aria-label="章节目录">${[...new Set(chs.map(c=>c.part))].map(part=>`<details class="side-section" open><summary>${esc(part)}</summary>${chs.filter(c=>c.part===part).map(c=>`<a href="#chapter/${c.id}" ${current===c.id?'aria-current="page"':''} class="${current===c.id?'active':''}"><span class="num">${c.id}</span><span>${esc(c.title.split('：')[0])}</span>${state.completed.includes(c.id)?'<span class="check" aria-label="已学">✓</span>':''}</a>`).join('')}</details>`).join('')}</nav><div class="side-bottom"><div>${state.completed.length} / 28 章已标记学完 <span style="float:right">${Math.round(state.completed.length/28*100)}%</span></div><div class="side-progress" role="progressbar" aria-label="手动标记的学习进度" aria-valuemin="0" aria-valuemax="28" aria-valuenow="${state.completed.length}"><i style="width:${state.completed.length/28*100}%"></i></div></div>`;
 $('#track-select').onchange=e=>{state.track=e.target.value;save();renderSidebar(current);if(route().view==='home')render(false);};$('.side-scroll').scrollTop=scroll;
}
function chapterRows(chs){return `<div class="chapter-grid">${chs.map(c=>`<a class="chapter-row" href="#chapter/${c.id}"><span class="chapter-number">${state.completed.includes(c.id)?'✓':c.id}</span><div class="row-copy"><h3>${esc(c.title)}</h3><p>${esc(c.deck)}</p><p style="margin-top:6px">${esc(c.courses.slice(0,2).join(' · '))}</p></div><span class="arrow" aria-hidden="true">↗</span></a>`).join('')}</div>`;}
const courseDescriptions={
 '线性代数':'形状、矩阵乘法、归一化、注意力与秩一更新。','概率论':'条件分布、采样、接受前缀与期望产出。','计算机组成':'数值表示、存储层级、SIMD/SIMT 与带宽。','计算机组成原理':'将逻辑计算映射到真正的硬件资源。','操作系统':'虚拟内存、工作集、DMA、调度与生命周期。','并行计算':'依赖图、异构平衡、内核、分块与流水。','数据结构':'页表、缓存键、组相联与布局契约。','算法设计':'top-k、分组、稀疏选择与成本权衡。','数值分析':'量化误差、归一化、求和顺序与容差。','数据库原理':'身份、快照、原子可见、提交与恢复。','计算机网络':'字节流、UTF-8、SSE 与协议边界。','软件工程':'接口、不变量、构建矩阵与可复现交付。','统计学':'留出轨迹、条件观测、分位数和重复实验。','分布式系统':'跨阶段状态、取消、代次与资源准入。','编译原理':'执行分派、图捕获与增量文本解析。','软件测试':'独立 oracle、负例与变形测试。','性能建模':'明确前提的下界、关键路径与收益估计。','排队论':'等待、公平、到达过程和尾延迟。'};
function architecture(){return `<div class="architecture" aria-label="GPU、RAM与SSD三层推理架构示意"><div class="eyebrow"><span>ONE MODEL · THREE TIERS</span><span>↗ SYSTEM VIEW</span></div><div class="arch-layer gpu"><div class="arch-label">GPU<small>工作集与计算</small></div><div style="flex:1"><strong>QSA · GDN · 热专家</strong><p>状态、密集算子与显存缓存</p><div class="expert-cells" aria-hidden="true">${Array.from({length:36},(_,i)=>`<i class="${i<21?'hot':''}"></i>`).join('')}</div></div></div><div class="arch-arrow"><span>↓ 激活 / 结果</span><span>↑ 专家 / 历史页</span></div><div class="arch-layer"><div class="arch-label">RAM<small>CPU 专家计算</small></div><div><strong>专家全集，或 GPU 缓存的补集</strong><p>锁页缓冲 · 主机历史状态</p></div></div><div class="arch-arrow"><span>↑ 按需读取与页面缓存</span></div><div class="arch-layer"><div class="arch-label">SSD<small>按行查询</small></div><div><strong>PLE / n-gram 模型表</strong><p>大容量不等于每步完整读取</p></div></div><div class="arch-caption">真正的问题不是“全部塞进显存”，而是哪些数据、在什么时刻、应出现在什么位置。示意非比例图。<a href="#source/S02">[S02]</a></div></div>`;}
function home(){const t=Book.tracks.find(t=>t.id===state.track),chs=Book.chapters.filter(c=>t.chapters.includes(c.id));return `<div class="hero"><div><span class="pill">独立开源项目教材 · EDITION 1.0</span><h1>从一个 token，<br><em>读懂计算机。</em></h1><p class="hero-intro">以 Strata 为线索，将线性代数、存储层级、并发与网络协议连成一门可实验的推理系统课程。先弄懂原理，再阅读代码，最后用证据说话。</p><div class="button-row"><a class="primary" href="#chapter/${state.last}">${state.last==='01'?'开始第一章':'继续第 '+state.last+' 章'} <span>→</span></a><a class="secondary" href="#labs">进入交互实验室</a></div><p class="micro">无需显卡即可学习与实验 · 无账户 / 无外部模型调用<br>研究日期 2026.10.04 · 上游锚点 ${Book.provenance.commit.slice(0,12)}</p></div>${architecture()}</div><div class="stats"><div class="stat"><strong>28</strong><span>完整章节</span></div><div class="stat"><strong>14</strong><span>交互实验</span></div><div class="stat"><strong>84</strong><span>解析自测</span></div><div class="stat"><strong>64</strong><span>教学学时</span></div></div><div class="section-head"><div><h2>找到适合你的入口</h2><p>同一本教材，三种深度；切换路线只改变目录，不删除内容。</p></div><a class="text-link" href="#teacher">教师手册 ↗</a></div><div class="track-grid">${Book.tracks.map((t,i)=>`<button class="track-card ${state.track===t.id?'active':''}" data-track="${t.id}"><span class="index">PATH 0${i+1}</span><strong>${esc(t.name)}</strong><span>${esc(t.desc)}</span><b>${t.chapters.length} 章 · ${esc(t.sub.split('·')[0])} →</b></button>`).join('')}</div><div class="section-head"><div><h2>把熟悉的大学课程接起来</h2><p>每一章都回答：这段实现，来自哪一种基本原理？</p></div><a class="text-link" href="#map">查看关联图 ↗</a></div><div class="filter-row">${['线性代数','概率论','计算机组成','操作系统','并行计算','数据库原理','计算机网络','软件工程'].map(c=>`<a class="filter-chip" href="#map/${encodeURIComponent(c)}">${c}</a>`).join('')}</div><div class="section-head"><div><h2>${esc(t.name)} · 章节目录</h2><p>理解 → 推导 → 源码 → 反例 → 实验 → 自测</p></div><button class="text-link" id="export-book">导出全文 HTML ↓</button></div>${chapterRows(chs)}${scope()}${footer()}`;}
function renderChapter(c){
 const prev=chapter(String(Number(c.id)-1).padStart(2,'0')),next=chapter(String(Number(c.id)+1).padStart(2,'0')),l=lab(c.lab);state.last=c.id;save();
 const quiz=c.quiz.map((q,i)=>{const a=state.answers[c.id+':'+i],check=a?.checked,correct=check&&a.choice===q.correct;return `<div class="quiz" data-q="${i}"><fieldset><legend>${i+1}. ${esc(q.text)}</legend>${q.choices.map((x,j)=>`<label><input type="radio" name="q-${i}" value="${j}" ${a?.choice===j?'checked':''}><span>${String.fromCharCode(65+j)}. ${esc(x)}</span></label>`).join('')}</fieldset><button class="secondary check-answer" data-index="${i}">核对答案</button><p class="feedback ${check?(correct?'correct':'incorrect'):''}" aria-live="polite">${check?(correct?'✓ 回答正确。':'↻ 再检查一下。')+esc(q.why):''}</p></div>`;}).join('');
 return `<div class="breadcrumbs"><a href="#home">课程</a><span>/</span><span>${esc(c.part)}</span><span>/</span><span>第 ${c.id} 章</span></div><header class="chapter-head"><span class="chapter-kicker">CHAPTER ${c.id} · ${esc(c.level)}${c.level==='扩展'?' / 非上游已审计实现':''}</span><h1>${esc(c.title)}</h1><p class="deck">${esc(c.deck)}</p><div class="chips">${c.courses.map(x=>`<a class="chip" href="#map/${encodeURIComponent(x)}">${esc(x)}</a>`).join('')}</div><div class="chapter-actions"><button class="secondary" id="complete-chapter">${state.completed.includes(c.id)?'✓ 已学完 · 撤销':'标记为已学完'}</button><button class="secondary" id="bookmark-chapter">${state.bookmarks.includes(c.id)?'★ 已收藏':'☆ 加入书签'}</button><button class="icon-button" id="font-smaller" aria-label="缩小正文字号">A−</button><button class="icon-button" id="font-larger" aria-label="增大正文字号">A+</button><button class="secondary" id="print-chapter">打印本章</button></div></header><div class="reading-layout"><article class="article"><div class="learning-goals"><span class="eyebrow">学习后，你应能做到</span><div class="goal-list">${c.goals.map((x,i)=>`<div class="goal"><i>0${i+1}</i><span>${esc(x)}</span></div>`).join('')}</div><p class="prereq">先修建议：${esc(c.prereq)}</p></div><div class="article-body">${bodyHTML(c.html)}</div>${l?`<div class="lab-link"><div><span class="eyebrow">把公式变成一次实验</span><h3>${esc(l.title)}</h3><p>${esc(l.description)}</p></div><a class="primary" href="#lab/${l.id}">打开实验 →</a></div>`:''}<div class="source-box"><h3>本章源码与原理索引</h3><p class="hint">链接固定到本版 SHA 的相关阅读窗口；接口事实不等于全路径运行验证。</p>${c.sources.map(id=>{let s=source(id);return s?`<a class="source-mini" href="#source/${id}"><code>${id}</code><span>${esc(s.title)}</span><span style="margin-left:auto">${s.kind}</span></a>`:'';}).join('')}</div><section class="quiz-section"><span class="eyebrow">CHECK YOUR UNDERSTANDING</span><h2>不靠猜，解释你选的答案</h2><p class="hint">3 道自测公开附解析，适合学习反馈，不作为保密考试。</p>${quiz}<h3 style="margin-top:30px">开放题 · 把条件说完整</h3><p style="font-size:14px;line-height:1.95">${esc(c.problem)}</p><details class="solution"><summary>展开参考论证与评分要点</summary><p>${esc(c.answer)}</p></details></section><section class="note-section" style="margin-top:30px"><h3>把自己的理解留下来</h3><label class="sr-only" for="chapter-note">第 ${c.id} 章个人笔记</label><textarea class="note-editor" id="chapter-note" maxlength="100000" placeholder="写下一个你原来理解错的地方，或者一个仍需验证的假设……">${esc(state.notes[c.id]||'')}</textarea><p class="hint" id="note-status">${storageOK?'笔记仅保存在此浏览器，可在“学习笔记”导出。':'本地存储不可用；记录仅保留在本次页面，请及时导出。'}</p></section><nav class="chapter-pagination" aria-label="前后章节">${prev?`<a href="#chapter/${prev.id}"><small>← 上一章 ${prev.id}</small>${esc(prev.title)}</a>`:'<a href="#home">← 回到课程首页</a>'}${next?`<a href="#chapter/${next.id}" style="text-align:right"><small>下一章 ${next.id} →</small>${esc(next.title)}</a>`:'<a href="#teacher">教师手册 →</a>'}</nav></article><aside class="toc" id="toc" aria-label="本章目录"></aside></div>${footer()}`;
}
function bindChapter(c){
 $('#complete-chapter').onclick=()=>{const i=state.completed.indexOf(c.id);if(i<0)state.completed.push(c.id);else state.completed.splice(i,1);save();$('#complete-chapter').textContent=state.completed.includes(c.id)?'✓ 已学完 · 撤销':'标记为已学完';renderSidebar(c.id);toast('学习进度已更新');};
 $('#bookmark-chapter').onclick=()=>{const i=state.bookmarks.indexOf(c.id);if(i<0)state.bookmarks.push(c.id);else state.bookmarks.splice(i,1);save();$('#bookmark-chapter').textContent=state.bookmarks.includes(c.id)?'★ 已收藏':'☆ 加入书签';};
 $('#font-smaller').onclick=()=>{state.fontSize=Math.max(15,state.fontSize-1);settings();save();};$('#font-larger').onclick=()=>{state.fontSize=Math.min(21,state.fontSize+1);settings();save();};$('#print-chapter').onclick=()=>window.print();
 $('#chapter-note').oninput=e=>{state.notes[c.id]=e.target.value;save();$('#note-status').textContent=storageOK?'已保存到本机。建议定期导出备份。':'本地存储不可用；请在离开页面前导出。';};
 $$('.quiz input').forEach(e=>e.onchange=()=>{const box=e.closest('.quiz'),i=box.dataset.q;state.answers[c.id+':'+i]={choice:Number(e.value),checked:false};box.querySelector('.feedback').textContent='';save();});
 $$('.check-answer').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.index),box=b.closest('.quiz'),picked=box.querySelector('input:checked'),fb=box.querySelector('.feedback');if(!picked){fb.className='feedback incorrect';fb.textContent='先选择一个答案，再核对解析。';return;}const choice=Number(picked.value),q=c.quiz[i],correct=choice===q.correct;state.answers[c.id+':'+i]={choice,checked:true};save();fb.className='feedback '+(correct?'correct':'incorrect');fb.textContent=(correct?'✓ 回答正确。':'↻ 再检查一下。')+q.why;});
 const heads=$$('.article-body h2');$('#toc').innerHTML=`<strong>本章导航</strong>${heads.map(h=>`<button data-target="${h.id}">${esc(h.textContent)}</button>`).join('')}<div class="toc-tools">${c.lab?`<a href="#lab/${c.lab}">↗ 本章实验</a>`:''}<a href="#sources">↗ 源码地图</a><a href="#notes">↗ 学习笔记</a></div>`;
 $$('#toc button').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.target).scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));
 if('IntersectionObserver'in window){observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){$$('#toc button').forEach(b=>b.classList.toggle('active',b.dataset.target===e.target.id));}}),{rootMargin:'-15% 0px -70% 0px'});heads.forEach(h=>observer.observe(h));}
}
function labsPage(category='全部'){const categories=['全部',...new Set(Book.labs.map(l=>l.category))];const ls=Book.labs.filter(l=>category==='全部'||l.category===category);return `<div class="page-head"><span class="eyebrow">THE INTERACTIVE LAB</span><h1>把推理系统，<em>拆成能动手的实验。</em></h1><p>调一个变量，先预测，再观察，再解释。所有数字来自明确的教学模型；不会偷偷调用远程模型，也不会把模拟包装成显卡跑分。</p></div><div class="filter-row">${categories.map(x=>`<a class="filter-chip ${category===x?'active':''}" href="#labs/${encodeURIComponent(x)}">${esc(x)}</a>`).join('')}</div><div class="lab-grid">${ls.map(l=>`<a class="lab-card" href="#lab/${l.id}"><span class="lab-num">LAB ${String(Book.labs.indexOf(l)+1).padStart(2,'0')} / ${esc(l.category)}</span><h3>${esc(l.title)}</h3><p>${esc(l.description)}</p><div class="lab-foot"><span>关联章节 ${l.chapters.join(' · ')}</span><span>开始实验 ↗</span></div></a>`).join('')}</div><div class="source-box"><h3>继续走向真实代码</h3><p class="hint">Python 标准库微型推理链：随机固定权重，完整走通输入、状态、MoE 与输出。不是 Strata 兼容实现，也不代表语言质量。</p><div class="button-row"><button class="secondary" data-asset="tiny_inference.py">下载微型引擎 ↓</button><button class="secondary" data-asset="test_tiny_inference.py">下载配套测试 ↓</button><button class="secondary" data-asset="labs-README.md">实验说明 ↓</button></div></div>${footer()}`;}
function labPage(l){return `<div class="breadcrumbs"><a href="#labs">交互实验室</a><span>/</span><span>${esc(l.category)}</span></div><div class="page-head"><span class="eyebrow">LAB ${String(Book.labs.indexOf(l)+1).padStart(2,'0')} · 教学推演，非硬件实测</span><h1>${esc(l.title)}</h1><p>${esc(l.description)}</p><div class="chips">${l.chapters.map(id=>`<a class="chip" href="#chapter/${id}">第 ${id} 章 · ${esc(chapter(id).title.split('：')[0])}</a>`).join('')}</div></div><div class="callout warn"><strong>模型边界：</strong>${esc(l.assumptions)}</div><div id="lab-mount"></div><div class="button-row"><button class="primary" id="save-experiment">保存本次实验记录</button><button class="secondary" id="export-experiment">导出参数与结果 JSON ↓</button><a class="secondary" href="#notes">查看实验笔记</a></div><div class="learning-goals" style="margin-top:28px"><span class="eyebrow">本次实验任务</span><p style="font-size:14px">${esc(l.task)}</p><p class="hint">保存时记录参数、结果、时间和“教学推演”标识。你的判断和反例可写入对应章节的笔记。</p></div>${footer()}`;}
function mapPage(selected=''){const courses=[...new Set(Book.chapters.flatMap(c=>c.courses))];const major=['线性代数','概率论','计算机组成','操作系统','并行计算','数据结构','算法设计','数值分析','数据库原理','计算机网络','软件工程','统计学'];const selectedCh=Book.chapters.filter(c=>!selected||c.courses.includes(selected));return `<div class="page-head"><span class="eyebrow">COMPUTER SCIENCE · CONNECTED</span><h1>不是另学一套黑话，<br><em>而是把基础知识接起来。</em></h1><p>同一段系统代码，往往同时涉及数学、状态与硬件。点击一门课，查看对应章节与可操作的问题。</p></div><div class="map-grid">${major.map(name=>{const count=Book.chapters.filter(c=>c.courses.includes(name)).length;return `<a class="map-card ${selected===name?'active':''}" href="#map/${encodeURIComponent(name)}"><strong>${esc(name)}</strong><p>${esc(courseDescriptions[name])}</p><span>${count} 个章节交叉关联 →</span></a>`;}).join('')}</div><div class="filter-row"><a class="filter-chip ${!selected?'active':''}" href="#map">全部课程</a>${courses.filter(c=>!major.includes(c)).map(c=>`<a class="filter-chip ${selected===c?'active':''}" href="#map/${encodeURIComponent(c)}">${esc(c)}</a>`).join('')}</div><div class="section-head"><div><h2>${esc(selected||'全部基础课程')} · ${selectedCh.length} 个章节</h2><p>${esc(courseDescriptions[selected]||'先修建议在每章开头；通识路线先用手算和浏览器模型建立直觉。')}</p></div></div>${chapterRows(selectedCh)}${footer()}`;}
function sourcesPage(){return `<div class="page-head"><span class="eyebrow">SOURCE ATLAS / 固定版本，不漂移</span><h1>每一个结论，<em>都能找到来处。</em></h1><p>19 个项目阅读入口，6 项基础原理 / 平台资料，8 份重点逻辑导读。代码窗口、接口契约、历史注释与真实运行是不同证据层次。</p></div><div class="callout"><strong>源码锚点：</strong><code style="overflow-wrap:anywhere">${Book.provenance.commit}</code><br>提交时间 ${Book.provenance.commitDate}；研究日期 ${Book.provenance.date}。未编译运行上游 GPU 引擎，未审阅用户多并发 fork。</div><div class="section-head"><h2>四个值得在课堂主动纠正的误读</h2></div><div class="map-grid" style="grid-template-columns:repeat(2,minmax(0,1fr))"><a class="map-card" href="#source/S04"><strong>48 层，不是 48 个 GDN 层</strong><p>当前几何为 36 GDN + 12 QSA；旧注释不应覆盖可执行定义。</p></a><a class="map-card" href="#source/S18"><strong>805,306,368 B = 768 MiB</strong><p>单位逐项验算，不把十进制 MB 与二进制 MiB 混用。</p></a><a class="map-card" href="#source/S11"><strong>八路轮换，不是 LRU</strong><p>判断替换算法要看实际状态更新，不凭缓存名称猜测。</p></a><a class="map-card" href="#source/S07"><strong>精确匹配，不照搬 p/q 公式</strong><p>经典投机采样和当前接口分开讲，状态与随机历史也需一致。</p></a></div><div class="section-head"><h2>项目代码与文档</h2><span class="hint">只对所列阅读范围负责</span></div><div class="source-grid">${Book.sources.filter(s=>s.id.startsWith('S')).map(sourceCard).join('')}</div><div class="section-head"><h2>大学基础与原始资料</h2></div><div class="source-grid">${Book.sources.filter(s=>s.id.startsWith('R')).map(sourceCard).join('')}</div><div class="scope-note">文件窗口的行号用于定位阅读范围，长文件没有全部审阅。代码导读中的节选会省略空白与无关上下文，完整实现请查看不可变链接。项目注释可能保留旧阶段叙述，不能只凭一句注释判断当前所有路径。</div>${footer()}`;}
function sourceCard(s){return `<a class="source-card" href="#source/${s.id}"><span class="source-id">${s.id}</span><span class="chip">${esc(s.kind)}</span><h3>${esc(s.title)}</h3>${s.path?`<code>${esc(s.path)} · L${s.start}–L${s.end}</code>`:''}<p>${esc(s.note)}</p></a>`;}
function sourcePage(s){const w=Book.walkthroughs.find(w=>w.source===s.id),chs=Book.chapters.filter(c=>c.sources.includes(s.id)||c.html.includes('['+s.id+']'));return `<div class="breadcrumbs"><a href="#sources">源码与原理地图</a><span>/</span><span>${s.id}</span></div><div class="page-head"><span class="eyebrow">${s.id} · ${esc(s.kind)}</span><h1>${esc(s.title)}</h1><p>${esc(s.note)}</p></div><div class="source-detail">${s.path?`<p class="path">${esc(s.path)}<br>阅读窗口 L${s.start}–L${s.end}<br>SHA ${Book.provenance.commit}</p>`:''}<a class="primary" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">打开${s.path?'固定版本源码窗口':'原始资料'} ↗</a>${s.id==='S19'?'<details class="solution"><summary>查看随教材附带的上游 MIT 许可</summary><pre><code>'+esc(Book.license)+'</code></pre></details>':''}<p class="hint">外部原始资料需要网络；课程内容与交互计算本身可以离线使用。${s.kind==='代码'?'接口注释与字段不等于所有分派路径都已执行验证。':''}</p></div>${w?`<h2>${esc(w.title)}</h2><p class="hint">核心逻辑摘编：省略无关上下文，部分片段为头文件数学说明；不是可单独编译的完整实现。</p><pre><code>${esc(w.code)}</code></pre><ol class="walk-steps">${w.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="callout warn">${esc(w.challenge)}</div>`:`<div class="callout"><strong>建议的阅读方法：</strong>先看输入、输出、所有者与有效期；再区分当前可执行字段、接口承诺与历史说明；最后找能推翻错误解释的最小测试。不要把一个文件窗口推断为整个工程的覆盖率。</div>`}<div class="section-head"><h2>在这些章节中使用</h2></div>${chs.length?chapterRows(chs):'<p class="hint">用于教材的发布、来源或许可说明。</p>'}${footer()}`;}
function weekTable(){return `<div class="table-wrap"><table><thead><tr><th>周</th><th>章节 / 主题</th><th>实验</th><th>本周交付</th></tr></thead><tbody>${Book.weeks.map(w=>`<tr><td>${w.week}</td><td><strong>${esc(w.title)}</strong><br>${w.chapters}</td><td>${esc(w.lab)}</td><td>${esc(w.deliverable)}</td></tr>`).join('')}</tbody></table></div>`;}
function teacherPage(){return `<div class="page-head"><span class="eyebrow">INSTRUCTOR'S FIELD GUIDE</span><h1>一门可以进入课堂的<em>系统课程。</em></h1><p>16 周、64 学时（每学时 45 分钟）、分层路线、形成性测验与课程项目。考核的是解释与证据，不是学生拥有什么显卡。</p></div><div class="button-row"><button class="primary" id="export-teacher">导出授课手册 HTML ↓</button><button class="secondary" id="export-book">导出全文与答案 HTML ↓</button><button class="secondary" data-asset="benchmark_template.csv">实测记录 CSV 模板 ↓</button><button class="secondary" data-asset="benchmark_protocol.md">实测协议 ↓</button></div><div class="section-head"><h2>16 周教学安排</h2><span class="hint">每周 2 理论 + 2 实验学时</span></div>${weekTable()}<div class="teacher-copy"><div class="article-body">${bodyHTML(Book.teacher)}</div></div>${footer()}`;}
function glossaryPage(query=''){const terms=Book.glossary.filter(t=>!query||(t.en+' '+t.zh+' '+t.meaning).toLowerCase().includes(query.toLowerCase()));return `<div class="page-head"><span class="eyebrow">GLOSSARY · ${Book.glossary.length} CONCEPTS</span><h1>术语不是门槛，<em>是索引。</em></h1><p>先读一句能理解的解释，再回到出现这个概念的章节。</p></div><label class="sr-only" for="glossary-query">搜索术语或解释</label><input class="glossary-search" id="glossary-query" placeholder="搜索 KV、操作系统、量化、state……" value="${esc(query)}"><div class="glossary-list" id="glossary-results">${terms.map(termHTML).join('')}</div>${footer()}`;}
function termHTML(t){return `<div class="term"><div class="en">${esc(t.en)}</div><h3>${esc(t.zh)}</h3><p>${esc(t.meaning)}</p><a href="#chapter/${t.chapter}">阅读第 ${t.chapter} 章 →</a></div>`;}
function quizStats(){let answered=0,correct=0;for(const c of Book.chapters)c.quiz.forEach((q,i)=>{const a=state.answers[c.id+':'+i];if(a?.checked){answered++;if(a.choice===q.correct)correct++;}});return {answered,correct};}
function notesPage(){const stats=quizStats(),notes=Book.chapters.filter(c=>state.notes[c.id]?.trim());return `<div class="page-head"><span class="eyebrow">YOUR LEARNING NOTEBOOK</span><h1>让理解，<em>留下可追踪的记录。</em></h1><p>本机保存的章节笔记、书签与实验参数。没有账户，不跨设备同步；导出 JSON 后可在另一浏览器导入。</p></div><div class="stats"><div class="stat"><strong>${state.completed.length}</strong><span>已学章节 / 28</span></div><div class="stat"><strong>${stats.correct}</strong><span>答对 / 已核对 ${stats.answered}</span></div><div class="stat"><strong>${notes.length}</strong><span>章节笔记</span></div><div class="stat"><strong>${state.experiments.length}</strong><span>实验快照</span></div></div><div class="button-row"><button class="primary" id="export-progress">导出学习记录 JSON ↓</button><button class="secondary" id="import-progress">导入并替换本机记录 ↑</button><button class="secondary" id="clear-progress">清空本机学习记录</button><input type="file" id="import-file" accept="application/json,.json" hidden></div><p class="hint">记录可由自己编辑，不作为考试成绩证明。导入将替换本机记录；请先备份。单次导入最大 2 MB，实验最多保留 40 份。</p><div class="section-head"><h2>我的书签</h2></div>${state.bookmarks.length?chapterRows(Book.chapters.filter(c=>state.bookmarks.includes(c.id))):'<div class="empty-state">在任意章节点击“加入书签”，就会出现在这里。</div>'}<div class="section-head"><h2>章节笔记</h2></div><div class="notes-grid">${notes.length?notes.map(c=>`<article class="saved-note"><div class="note-head"><h3><a href="#chapter/${c.id}">${c.id} · ${esc(c.title)}</a></h3><span class="chip">仅本机</span></div><p>${esc(state.notes[c.id])}</p></article>`).join(''):'<div class="empty-state">每章末尾都可以记录一个新理解、一个反例或一个待验证问题。</div>'}</div><div class="section-head"><h2>实验快照</h2></div><div class="notes-grid">${state.experiments.length?[...state.experiments].reverse().map((e,i)=>`<article class="saved-note"><div class="note-head"><div><h3><a href="#lab/${e.lab}">${esc(lab(e.lab).title)}</a></h3><p class="hint">${esc(e.time)} · 教学推演，非硬件实测</p></div><button class="secondary delete-experiment" data-index="${state.experiments.length-1-i}">删除</button></div><details class="solution"><summary>查看保存的参数与完整结果</summary><pre><code>${esc(JSON.stringify({params:e.params,result:e.result},null,2))}</code></pre></details></article>`).join(''):'<div class="empty-state">在交互实验末尾点击“保存本次实验记录”，保留参数与结果。</div>'}</div>${footer()}`;}
function exportFile(text,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function absoluteRefs(html){return refs(html).replace(/href="#source\/((?:S|R)\d{2})"/g,(m,id)=>`href="${source(id).url}"`);}
const staticStyle=`body{font-family:system-ui,"PingFang SC","Microsoft YaHei",sans-serif;color:#16332a;background:#fff;max-width:950px;margin:40px auto;padding:0 25px;line-height:1.95;font-size:17px}h1{font-size:36px;line-height:1.5}h2{font-size:24px;margin-top:34px}h3{font-size:19px}a{color:#14664e}pre{background:#f1f5ef;padding:18px;overflow:auto;white-space:pre;font-size:12px;line-height:1.8}code{font-family:monospace}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border:1px solid #d5dfd3;padding:10px;text-align:left}th{background:#eef3e9}.equation{background:#eef5e7;border:1px solid #d5dfd3;padding:16px;margin:24px 0;overflow-wrap:anywhere}.chapter-print{border-top:2px solid #14664e;padding-top:30px;margin-top:55px}.ref{font-size:11px;margin-left:4px}summary{cursor:pointer;color:#14664e}details{margin:20px 0}.metadata{font-size:13px;color:#526358}li{margin-bottom:9px}@media print{body{font-size:11pt;margin:0;max-width:none}.chapter-print{page-break-before:always}h2,h3{break-after:avoid}pre,.equation{break-inside:avoid}@page{margin:18mm}}`;
function documentHTML(title,body){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>${staticStyle}</style></head><body><h1>${esc(title)}</h1><p class="metadata">独立教学初版 1.0 · 2026-10-04 · 固定 SHA ${Book.provenance.commit}<br>未编译运行上游 GPU 引擎；模拟值不是真实跑分；源码阅读范围见索引。<br>作者：${esc(Book.provenance.author)} · 许可：${esc(Book.provenance.license)} · 勘误：${esc(Book.provenance.issues)}</p>${body}</body></html>`;}
function fullBook(){return documentHTML('从 Strata 学推理系统 · 全文与练习解析',`<p>28 章 · 84 道选择题及解析 · 28 道开放题 · 16 周授课方案。浏览器交互实验请使用主站 / 单文件交互版。</p><ol>${Book.chapters.map(c=>`<li><a href="#chapter-${c.id}">${esc(c.title)}</a></li>`).join('')}</ol>${Book.chapters.map(c=>`<section class="chapter-print" id="chapter-${c.id}"><p class="metadata">CHAPTER ${c.id} · ${esc(c.part)} · ${esc(c.courses.join(' / '))}</p><h1>${esc(c.title)}</h1><p>${esc(c.deck)}</p><p class="metadata">先修：${esc(c.prereq)}<br>学习目标：${esc(c.goals.join('；'))}</p>${absoluteRefs(c.html).replace(/id="sec-(\d+)"/g,`id="c${c.id}-sec-$1"`)}<h2>自测与参考答案</h2>${c.quiz.map((q,i)=>`<h3>${i+1}. ${esc(q.text)}</h3><p>${q.choices.map((a,j)=>String.fromCharCode(65+j)+'. '+esc(a)).join('<br>')}</p><p><strong>答案 ${String.fromCharCode(65+q.correct)}。</strong>${esc(q.why)}</p>`).join('')}<h3>开放题</h3><p>${esc(c.problem)}</p><p><strong>参考论证：</strong>${esc(c.answer)}</p></section>`).join('')}<section class="chapter-print"><h1>教师手册</h1>${weekTable()}${absoluteRefs(Book.teacher)}</section><section class="chapter-print"><h1>源码与原理索引</h1>${Book.sources.map(s=>`<p><strong>${s.id} · ${esc(s.title)}</strong><br>${esc(s.note)}<br><a href="${s.url}">${esc(s.url)}</a></p>`).join('')}<h2>上游源码许可</h2><pre><code>${esc(Book.license)}</code></pre></section>`);}
function bindCommon(){
 $$('[data-track]').forEach(b=>b.onclick=()=>{state.track=b.dataset.track;save();render(false);});
 $$('[data-asset]').forEach(b=>b.onclick=()=>{const name=b.dataset.asset;if(Book.assets[name]){exportFile(Book.assets[name],name);toast('已导出 '+name);}else toast('该素材在完整源码包中。');});
 if($('#export-book'))$('#export-book').onclick=()=>exportFile(fullBook(),'Strata-推理系统-全文与解析.html','text/html;charset=utf-8');
 if($('#export-teacher'))$('#export-teacher').onclick=()=>exportFile(documentHTML('从 Strata 学推理系统 · 教师手册',weekTable()+absoluteRefs(Book.teacher)),'Strata-教师手册.html','text/html;charset=utf-8');
}
function bindNotes(){
 $('#export-progress').onclick=()=>exportFile(JSON.stringify({exportedAt:new Date().toISOString(),edition:Book.provenance.edition,commit:Book.provenance.commit,...state},null,2),'Strata-学习记录.json','application/json');
 $('#import-progress').onclick=()=>$('#import-file').click();
 $('#import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw new Error('文件超过 2 MB');const parsed=validate(JSON.parse(await file.text()));if(!confirm('导入将替换此浏览器的学习记录。确认已备份后继续？'))return;state=parsed;save();settings();render(false);toast('学习记录已导入');}catch(err){toast('导入失败：'+err.message);}};
 $('#clear-progress').onclick=()=>{if(!confirm('确定清空本机的进度、笔记、书签与实验记录？此操作不能撤销，建议先导出。'))return;const theme=state.theme;state=initial();state.theme=theme;save();settings();render(false);toast('本机学习记录已清空');};
 $$('.delete-experiment').forEach(b=>b.onclick=()=>{state.experiments.splice(Number(b.dataset.index),1);save();render(false);});
}
function route(){try{const p=location.hash.replace(/^#\/?/,'').split('/').map(decodeURIComponent);return {view:p[0]||'home',arg:p[1]||''};}catch(e){return {view:'home',arg:''};}}
function render(scroll=true){
 if(observer){observer.disconnect();observer=null;}labSnapshot=null;const r=route();let html='',title='';
 const c=r.view==='chapter'?chapter(r.arg):null,l=r.view==='lab'?lab(r.arg):null,s=r.view==='source'?source(r.arg):null;
 if(r.view==='home'){html=home();title='从一个 token，读懂计算机';}
 else if(c){html=renderChapter(c);title=c.title;}
 else if(r.view==='labs'){html=labsPage(r.arg||'全部');title='交互实验室';}
 else if(l){html=labPage(l);title=l.title;}
 else if(r.view==='map'){html=mapPage(r.arg);title='基础课程关联图';}
 else if(r.view==='sources'){html=sourcesPage();title='源码地图';}
 else if(s){html=sourcePage(s);title=s.title;}
 else if(r.view==='teacher'){html=teacherPage();title='教师手册';}
 else if(r.view==='glossary'){html=glossaryPage();title='术语表';}
 else if(r.view==='notes'){html=notesPage();title='学习笔记';}
 else{html=`<div class="page-head"><h1>这个学习入口不存在。</h1><p>章节和实验都可以从目录找到；未知地址不会触发任何远程请求。</p><a class="primary" href="#home">回到课程首页</a></div>`;title='未找到页面';}
 $('#main').innerHTML='<div class="page"><div id="storage-alert" class="callout warn" role="status" '+(storageOK?'hidden':'')+'>本地存储当前不可用，或旧记录无法解析；本次学习记录暂存于页面内存。请在关闭前导出 JSON，勿把它当作已持久保存。</div>'+draftNote()+html+'</div>';document.title=title+' · 从 Strata 学推理系统';document.body.dataset.view=r.view;
 renderSidebar(c?.id);$$('.top-nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===r.view||(r.view==='chapter'&&a.dataset.view==='home')||(r.view==='lab'&&a.dataset.view==='labs')||(r.view==='source'&&a.dataset.view==='sources')));settings();bindCommon();
 if(c)bindChapter(c);
 if(l){labSnapshot=LabViews.mount(l.id,$('#lab-mount'));$('#save-experiment').onclick=()=>{const e=labSnapshot?.();if(!e){toast('参数无效，不能保存');return;}state.experiments.push({...e,time:new Date().toISOString()});state.experiments=state.experiments.slice(-40);save();toast('已保存到学习笔记');};$('#export-experiment').onclick=()=>{const e=labSnapshot?.();if(!e){toast('参数无效，不能导出');return;}exportFile(JSON.stringify({...e,time:new Date().toISOString(),edition:Book.provenance.edition},null,2),'Strata-lab-'+l.id+'.json','application/json');};}
 if(r.view==='glossary')$('#glossary-query').oninput=e=>{const q=e.target.value.toLowerCase().trim();$('#glossary-results').innerHTML=Book.glossary.filter(t=>(t.en+' '+t.zh+' '+t.meaning).toLowerCase().includes(q)).map(termHTML).join('')||'<div class="empty-state">没有匹配术语，试试全文搜索。</div>';};
 if(r.view==='notes')bindNotes();document.body.classList.remove('sidebar-open');$('#menu-button').setAttribute('aria-expanded','false');if(scroll)window.scrollTo({top:0,behavior:'instant'});
}
function highlight(text,q){const i=text.toLowerCase().indexOf(q.toLowerCase());if(i<0)return esc(text);return esc(text.slice(0,i))+'<mark>'+esc(text.slice(i,i+q.length))+'</mark>'+esc(text.slice(i+q.length));}
function searchNow(q){q=q.trim();const out=$('#search-results');if(!q){out.innerHTML='<p class="modal-hint">试试“128”“残差”“只回退”“SSE”或某门基础课。正文、标题和术语均可检索。</p>';return;}
 const tokens=q.toLowerCase().split(/\s+/),hits=Book.chapters.map(c=>{const plain=c.title+' '+c.courses.join(' ')+' '+c.plain;let score=tokens.every(t=>plain.toLowerCase().includes(t))?1:0;if(score&&c.title.toLowerCase().includes(q.toLowerCase()))score+=10;return {c,plain,score};}).filter(x=>x.score).sort((a,b)=>b.score-a.score);
 const terms=Book.glossary.filter(t=>(t.en+' '+t.zh+' '+t.meaning).toLowerCase().includes(q.toLowerCase())).slice(0,5),sources=Book.sources.filter(s=>(s.id+' '+s.title+' '+s.note).toLowerCase().includes(q.toLowerCase())).slice(0,3);
 out.innerHTML=`<p class="modal-hint">${hits.length} 个章节匹配 · ${terms.length} 个术语 · ${sources.length} 项来源（每类展示有上限）</p>`+hits.slice(0,10).map(({c,plain})=>{const at=plain.toLowerCase().indexOf(tokens[0]),start=Math.max(0,at-35),snippet=plain.slice(start,start+130);return `<a class="search-result" href="#chapter/${c.id}"><small>CHAPTER ${c.id}</small><strong>${highlight(c.title,q)}</strong><p>${start?'…':''}${highlight(snippet,q)}…</p></a>`;}).join('')+terms.map(t=>`<a class="search-result" href="#chapter/${t.chapter}"><small>术语 · ${esc(t.en)}</small><strong>${highlight(t.zh,q)}</strong><p>${highlight(t.meaning,q)}</p></a>`).join('')+sources.map(s=>`<a class="search-result" href="#source/${s.id}"><small>${s.id} · 来源</small><strong>${highlight(s.title,q)}</strong><p>${highlight(s.note,q)}</p></a>`).join('');
 if(!hits.length&&!terms.length&&!sources.length)out.innerHTML='<div class="empty-state">没有找到匹配内容。可尝试较短关键词，如“状态”“量化”“页表”。</div>';
}
function openSearch(){const dialog=$('#search-dialog');if(!dialog.open)dialog.showModal();$('#global-search').value='';searchNow('');setTimeout(()=>$('#global-search').focus(),0);}
$('#search-button').onclick=openSearch;$('#close-search').onclick=()=>$('#search-dialog').close();$('#global-search').oninput=e=>searchNow(e.target.value);$('#search-dialog').addEventListener('click',e=>{if(e.target===$('#search-dialog'))$('#search-dialog').close();});
$('#theme-button').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';save();settings();};$('#menu-button').onclick=()=>{document.body.classList.toggle('sidebar-open');$('#menu-button').setAttribute('aria-expanded',document.body.classList.contains('sidebar-open'));};$('#sidebar-overlay').onclick=()=>{document.body.classList.remove('sidebar-open');$('#menu-button').setAttribute('aria-expanded','false');};
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a&&$('#search-dialog').open)$('#search-dialog').close();});
document.addEventListener('keydown',e=>{const editing=/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement.tagName);if((e.key==='k'&&(e.metaKey||e.ctrlKey))||(e.key==='/'&&!editing)){e.preventDefault();openSearch();}if(e.key==='Escape'){document.body.classList.remove('sidebar-open');$('#menu-button').setAttribute('aria-expanded','false');}if(!editing&&!$('#search-dialog').open&&route().view==='chapter'&&(e.key==='['||e.key===']')){const n=Number(route().arg)+(e.key==='['?-1:1),id=String(n).padStart(2,'0');if(chapter(id))location.hash='#chapter/'+id;}});
window.addEventListener('hashchange',()=>render(true));settings();render(false);
// Exposed only for inspectable local QA and export, never for model/API calls.
window.Textbook={edition:Book.provenance.edition,validateRecord:validate,makeFullBook:fullBook,book:Book};
})();
